name: build-dist

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show tool versions
        working-directory: js
        run: |
          node -v
          npm -v

      - name: Assert entrypoints exist (forum.js/admin.js)
        run: |
          if [ ! -f js/forum.js ] || [ ! -f js/admin.js ]; then
            echo "::error::Missing js/forum.js or js/admin.js. Per Flarum 1.x docs, these are REQUIRED entrypoints that re-export ./src code."
            echo "Example:"
            echo "  // js/forum.js"
            echo "  export * from './src/forum';"
            echo "  // js/admin.js"
            echo "  export * from './src/admin';"
            exit 1
          fi

      - name: Install deps
        working-directory: js
        run: |
          npm ci || npm i

      - name: Build (flarum-webpack-config)
        working-directory: js
        run: |
          npx webpack --mode production
          echo "== After build, list js/dist =="
          ls -lah dist || true

      - name: Assert dist produced
        run: |
          echo "== List js/dist =="
          ls -lah js/dist || true
          test -f js/dist/forum.js || { echo "::error::js/dist/forum.js not found after build"; exit 1; }
          test -f js/dist/admin.js || { echo "::error::js/dist/admin.js not found after build"; exit 1; }

      - name: Commit dist (force add even if ignored)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f js/dist
          if ! git diff --cached --quiet; then
            git commit -m "build: update dist [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload dist as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: js-dist
          path: js/dist
